name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Enable corepack
        run: corepack enable
      - name: Install deps
        run: pnpm install --frozen-lockfile=false
      - name: Lint
        run: pnpm run lint
      - name: Unit tests
        run: pnpm run test
      - name: Build
        run: pnpm run build
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: E2E tests
        run: pnpm run test:e2e
